name: emptyapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  firebase_core: 2.25.4
  firebase_auth: ^4.4.0
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.5.3
  flutter_launcher_icons: ^0.9.2
  carousel_slider: ^4.0.0
  location: ^5.0.3
  cloud_firestore: ^4.15.4
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

webdev: ^3.0.0


flutter:
  uses-material-design: true
